# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title simulate_system
#' @description Simulate the time evaluation of the diffusion of intracutaneously applied capsaicin-evoked pain mediated by the spinal cord.
#' @details The model is build from 4 compartments. 1 The peripheral compartment; 2 The central compartment; 3 The transit compartment; 4 The effect compartment
#' @param compartments Tow-dimensional representation of model compartments.
#' @param q Clearance of the capsaicin conentration in the peripheral compartment of the subcutaneous fat tissue.
#' @param ec50 Effect activity triggered by capsaicin concentration of the peripheral compartment in the transit compartment.
#' @param n The Hill coefficient as a measure of ultrasensitivity.
#' @param kin Apparent effect production rate in the transit compartment.
#' @param diff_coeff Lateral diffusion coefficient for the pain stimulus diffusion within the transit compartment.
#' @param tau Decay time that describes the decay of the effect in the transit compartment.
#' @param omega Threshold of severity perception of a pain stimulus.
#' @param t Duration of the simulation.
#' @param inc Number of simulated increments.
#' @return Tow-dimensional representation of model compartments. 4 Compartments.
#' @export
simulate_system <- function(compartments, q, ec50, n, kin, diff_coeff, tau, omega, t, inc) {
    .Call(`_pguPainDiffusion_simulate_system`, compartments, q, ec50, n, kin, diff_coeff, tau, omega, t, inc)
}

